### ISSUE TITLE
Missing shellenv dependency

### ISSUE THREAD

**Issue by Tomcat-Engineering** [noonat/sublime-gofmt#1]
I get an error message `ImportError: No module named 'shellenv'`

[According to the golangconfig docs, you should mention this as a dependency](https://go.googlesource.com/sublime-config/+/HEAD/docs/package_developer.md#Requiring-the-Dependency)

**Comment by metaleap** [comment]
Same prob here

**Comment by noonat** [comment]
@Tomcat-Engineering  @metaleap I ran into this issue myself on a fresh install of ST3, and I've fixed it in v0.1.2.
