### ISSUE TITLE
 when `ctrl + s` formatting the go code, It can hiding my terminal(third pane) pane, that is normal? 

### ISSUE THREAD

**Issue by cycold** [noonat/sublime-gofmt#14]
Could give a config option for format the code not trigger the hiding pane action.

There I hope keep the terminal pane alive rather than hide when formatting go code.

I'm using this plugin Terminus https://github.com/randy3k/Terminus

![image](https://user-images.githubusercontent.com/2446601/68465208-f76b5d00-024c-11ea-9f0c-ced2e8cae619.png)

ps: Poor English...

**Comment by noonat** [comment]
@cycold This definitely isn't intentional. I'll take a look and see if I can figure out what's going on with it.

**Comment by noonat** [comment]
It seems like this is a general issue that affects all plugins when using the console (bottom panel) for things. The same thing happens with the regular console when you save. From experimentation, if you instead split your view into two rows (View -> Layout -> Rows: 2) and then open a terminal there (Command Palette -> Terminus: Open Default Shell In View) then that will stay open when you save.
