### ISSUE TITLE
Palette command is missing?

### ISSUE THREAD

**Issue by ghost** [noonat/sublime-gofmt#2]
I'm running ST3 build 3126 on macOS 10.12.4. After installing Gofmt (v0.1.1), I can't find the palette command "Gofmt". Restarting ST3 doesn't help. Restarting the computer doesn't help either.

**Comment by cschar** [comment]
same

**Comment by noonat** [comment]
I haven't been able to reproduce this with ST3 build 3143. Does this still happen for you with v0.1.2?

**Comment by ghost** [comment]
I've updated and I now see the palette command! I'm also on ST3 build 3143

**Comment by noonat** [comment]
@spencer-rig Awesome, glad to hear it! Thanks for letting me know.
