### ISSUE TITLE
Error trying to parse package file trailing comma before closing bracket sublime 2

### ISSUE THREAD

**Issue by christopherreay** [noonat/sublime-gofmt#3]
This is the response from sublime two when trying to install the package

![screenshot from 2017-08-25 17 04 23](https://user-images.githubusercontent.com/239550/29736604-b7a28118-89b7-11e7-9849-3b3a6ec59cc5.png)

**Comment by noonat** [comment]
I fixed this trailing comma issue. I haven't tested this package in ST2, but if this works for you there, please let me know and I'll mark it as compatible with ST2.
