### ISSUE TITLE
Viewport moves up exactly one line on format

### ISSUE THREAD

**Issue by JeanMertz** [noonat/sublime-gofmt#6]
Whenever I format a file (either through saving, or `Gofmt: Format this file`), the viewport moves up exactly one line. The actual cursor stays where it's supposed to be, but the view simply shifts up.

This happens both with the default `gofmt`, and with my custom config for `goimports`:

```json
{
  "cmds": [
    ["goimports", "-e"]
  ],
  "format_on_save": true
}
```

**Comment by noonat** [comment]
This should be fixed now (see #7).
